### ISSUE TITLE
Getting interval endpoints / time population size pairs

### ISSUE THREAD

**Issue by zholzer** [rbouckaert/biceps#3]
Is there a way to get the exact x and y value for all times and population sizes respectively? Currently, the log outputs PopSizes and GroupSizes for each epoch, but not the endpoints of the epochs. I would like to be able to plot the exact outputs of the mean etc on a graph. Are the values outputted from Tracer the exact x and y values, or are they being smoothed for the graph? If they are not exact values, can I reconstruct the interval endpoints from the BEAST output files? Thank you!

**Comment by rbouckaert** [comment]
I tried to explain here: https://groups.google.com/g/beast-users/c/LuZ9d14or08
